name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generates the snake files into the dist/ directory
      - name: Generate Snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Directly deploys the contents of the dist folder to your output branch
      - name: Deploy to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          token: ${{ secrets.GITHUB_TOKEN }}
